server:
  port: 8095
eureka:
  client:
    # 表示eureka client间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 30 # 默认30秒
    service-url:
      defaultZone: http://localhost:8091/eureka/
spring:
  application:
    name: eureka-client-ribbon
  zipkin:
    base-url: http://127.0.0.1:9411