server:
  port: 8095
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
eureka:
  instance:
    metadata-map:
      cluster: ribbon # turbine被监控客户端的配置：需要配置集群名
  client:
    # 表示eureka client间隔多久重新拉取服务注册信息
    registry-fetch-interval-seconds: 5 # 默认30秒
    service-url:
      defaultZone: http://localhost:8091/eureka/